// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

package test3

import "github.com/iotaledger/wasp/packages/vm/wasmlib/go/wasmlib"

type AddMaterialCall struct {
	Func    *wasmlib.ScFunc
	Params  MutableAddMaterialParams
}

type AddPPToFractionCall struct {
	Func    *wasmlib.ScFunc
	Params  MutableAddPPToFractionParams
}

type CreateFractionCall struct {
	Func    *wasmlib.ScFunc
	Params  MutableCreateFractionParams
}

type CreatePPCall struct {
	Func    *wasmlib.ScFunc
	Params  MutableCreatePPParams
	Results ImmutableCreatePPResults
}

type InitCall struct {
	Func    *wasmlib.ScInitFunc
	Params  MutableInitParams
}

type SetMaterialsCall struct {
	Func    *wasmlib.ScFunc
	Params  MutableSetMaterialsParams
}

type SetOwnerCall struct {
	Func    *wasmlib.ScFunc
	Params  MutableSetOwnerParams
}

type GetAmountOfRequiredFundsCall struct {
	Func    *wasmlib.ScView
	Params  MutableGetAmountOfRequiredFundsParams
	Results ImmutableGetAmountOfRequiredFundsResults
}

type GetMaterialsCall struct {
	Func    *wasmlib.ScView
	Params  MutableGetMaterialsParams
	Results ImmutableGetMaterialsResults
}

type GetOwnerCall struct {
	Func    *wasmlib.ScView
	Results ImmutableGetOwnerResults
}

type GetPPCall struct {
	Func    *wasmlib.ScView
	Params  MutableGetPPParams
	Results ImmutableGetPPResults
}

type GetTokenPerPackageCall struct {
	Func    *wasmlib.ScView
	Params  MutableGetTokenPerPackageParams
	Results ImmutableGetTokenPerPackageResults
}

type Funcs struct{}

var ScFuncs Funcs

func (sc Funcs) AddMaterial(ctx wasmlib.ScFuncCallContext) *AddMaterialCall {
	f := &AddMaterialCall{Func: wasmlib.NewScFunc(ctx, HScName, HFuncAddMaterial)}
	f.Func.SetPtrs(&f.Params.id, nil)
	return f
}

func (sc Funcs) AddPPToFraction(ctx wasmlib.ScFuncCallContext) *AddPPToFractionCall {
	f := &AddPPToFractionCall{Func: wasmlib.NewScFunc(ctx, HScName, HFuncAddPPToFraction)}
	f.Func.SetPtrs(&f.Params.id, nil)
	return f
}

func (sc Funcs) CreateFraction(ctx wasmlib.ScFuncCallContext) *CreateFractionCall {
	f := &CreateFractionCall{Func: wasmlib.NewScFunc(ctx, HScName, HFuncCreateFraction)}
	f.Func.SetPtrs(&f.Params.id, nil)
	return f
}

func (sc Funcs) CreatePP(ctx wasmlib.ScFuncCallContext) *CreatePPCall {
	f := &CreatePPCall{Func: wasmlib.NewScFunc(ctx, HScName, HFuncCreatePP)}
	f.Func.SetPtrs(&f.Params.id, &f.Results.id)
	return f
}

func (sc Funcs) Init(ctx wasmlib.ScFuncCallContext) *InitCall {
	f := &InitCall{Func: wasmlib.NewScInitFunc(ctx, HScName, HFuncInit, keyMap[:], idxMap[:])}
	f.Func.SetPtrs(&f.Params.id, nil)
	return f
}

func (sc Funcs) SetMaterials(ctx wasmlib.ScFuncCallContext) *SetMaterialsCall {
	f := &SetMaterialsCall{Func: wasmlib.NewScFunc(ctx, HScName, HFuncSetMaterials)}
	f.Func.SetPtrs(&f.Params.id, nil)
	return f
}

func (sc Funcs) SetOwner(ctx wasmlib.ScFuncCallContext) *SetOwnerCall {
	f := &SetOwnerCall{Func: wasmlib.NewScFunc(ctx, HScName, HFuncSetOwner)}
	f.Func.SetPtrs(&f.Params.id, nil)
	return f
}

func (sc Funcs) GetAmountOfRequiredFunds(ctx wasmlib.ScViewCallContext) *GetAmountOfRequiredFundsCall {
	f := &GetAmountOfRequiredFundsCall{Func: wasmlib.NewScView(ctx, HScName, HViewGetAmountOfRequiredFunds)}
	f.Func.SetPtrs(&f.Params.id, &f.Results.id)
	return f
}

func (sc Funcs) GetMaterials(ctx wasmlib.ScViewCallContext) *GetMaterialsCall {
	f := &GetMaterialsCall{Func: wasmlib.NewScView(ctx, HScName, HViewGetMaterials)}
	f.Func.SetPtrs(&f.Params.id, &f.Results.id)
	return f
}

func (sc Funcs) GetOwner(ctx wasmlib.ScViewCallContext) *GetOwnerCall {
	f := &GetOwnerCall{Func: wasmlib.NewScView(ctx, HScName, HViewGetOwner)}
	f.Func.SetPtrs(nil, &f.Results.id)
	return f
}

func (sc Funcs) GetPP(ctx wasmlib.ScViewCallContext) *GetPPCall {
	f := &GetPPCall{Func: wasmlib.NewScView(ctx, HScName, HViewGetPP)}
	f.Func.SetPtrs(&f.Params.id, &f.Results.id)
	return f
}

func (sc Funcs) GetTokenPerPackage(ctx wasmlib.ScViewCallContext) *GetTokenPerPackageCall {
	f := &GetTokenPerPackageCall{Func: wasmlib.NewScView(ctx, HScName, HViewGetTokenPerPackage)}
	f.Func.SetPtrs(&f.Params.id, &f.Results.id)
	return f
}
