// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

package test3

import "github.com/iotaledger/wasp/packages/vm/wasmlib/go/wasmlib"

type ArrayOfImmutableComposition struct {
	objID int32
}

func (a ArrayOfImmutableComposition) Length() int32 {
	return wasmlib.GetLength(a.objID)
}

func (a ArrayOfImmutableComposition) GetComposition(index int32) ImmutableComposition {
	return ImmutableComposition{objID: a.objID, keyID: wasmlib.Key32(index)}
}

type ImmutableCompositions = ArrayOfImmutableComposition

type ArrayOfMutableComposition struct {
	objID int32
}

func (a ArrayOfMutableComposition) Clear() {
	wasmlib.Clear(a.objID)
}

func (a ArrayOfMutableComposition) Length() int32 {
	return wasmlib.GetLength(a.objID)
}

func (a ArrayOfMutableComposition) GetComposition(index int32) MutableComposition {
	return MutableComposition{objID: a.objID, keyID: wasmlib.Key32(index)}
}

type MutableCompositions = ArrayOfMutableComposition

type ArrayOfImmutableFracComposition struct {
	objID int32
}

func (a ArrayOfImmutableFracComposition) Length() int32 {
	return wasmlib.GetLength(a.objID)
}

func (a ArrayOfImmutableFracComposition) GetFracComposition(index int32) ImmutableFracComposition {
	return ImmutableFracComposition{objID: a.objID, keyID: wasmlib.Key32(index)}
}

type ImmutableFracCompositions = ArrayOfImmutableFracComposition

type ArrayOfMutableFracComposition struct {
	objID int32
}

func (a ArrayOfMutableFracComposition) Clear() {
	wasmlib.Clear(a.objID)
}

func (a ArrayOfMutableFracComposition) Length() int32 {
	return wasmlib.GetLength(a.objID)
}

func (a ArrayOfMutableFracComposition) GetFracComposition(index int32) MutableFracComposition {
	return MutableFracComposition{objID: a.objID, keyID: wasmlib.Key32(index)}
}

type MutableFracCompositions = ArrayOfMutableFracComposition
