name: test3
description: test3 description
events:
  payout:
structs:
  ProductPass:
    id: Hash
    did: String //merged did:iota:id
    name: String
    issuer: AgentID //packaging producer
    amount: Int64
    version: Uint8
    decFood: Bool
    decHygiene: Bool
    chargeWeight: Uint64
    packageWeight: Uint64
  Composition:
    material: String
    proportion: Uint8
  Fraction:
    fracId: Hash
    did: String
    name: String
    decFood: Bool
    decHygiene: Bool
    issuer: AgentID
    amount: Int64
  FracComposition:
    material: String
    weight: Uint64 //in mg
  Recyclate:
    recyId: Hash
    did: String
    name: String
    decFood: Bool
    decHygiene: Bool
    issuer: AgentID
    amount: Int64
    fracId: Hash
  RecyComposition:
    material: String
    weight: Uint64 //in mg 
typedefs:
  Compositions: Composition[]
  FracCompositions: FracComposition[]
  FracPayoffKeys: AgentID[]
  FracPayoffs: map[AgentID]Uint64
  RecyCompositions: RecyComposition[]
state:
  owner: AgentID // current owner of this smart contract
  productpasses: map[Hash]ProductPass
  compositions: map[Hash]Compositions
  shareRecycler: Uint8
  pricePerMg: Uint64
  fractions: map[Hash]Fraction
  fracCompositions: map[Hash]FracCompositions
  recyclates: map[Hash]Recyclate
  recyCompositions: map[Hash]RecyCompositions
  payoffsFrac: map[Hash]FracPayoffs
  payoffKeysFrac: map[Hash]FracPayoffKeys
  lastPayout: Int64
funcs:
  init:
    params:
      owner: AgentID? // optional owner of this smart contract
  createPP:
    params: 
      name: String
    results:
      id: Hash
  addMaterial:
    params:
      id: Hash
      mat: String
      prop: Uint8
  setMaterials:
    params:
      id: Hash
      comp: Compositions?
  setOwner:
    access: owner // current owner of this smart contract
    params:
      owner: AgentID // new owner of this smart contract
  createFraction:
    params:
      name: String?
    results:
      fracID: Hash
  addPPToFraction:
    params:
      ppID: Hash
      fracID: Hash
    results:
      pp: ProductPass
      fracID: Hash
  createRecyclate:
    params:
      fracID: Hash
      name: String?
    results:
      fraction: Fraction
      recyclateID: Hash
  payoutFrac:
    params:
      fracID: Hash
views:
  getPP:
    params: 
      id: Hash
    results: 
      ppresult: ProductPass
      ppname: String
  getMaterials:
    params:
      id: Hash
    results:
      compositions: Compositions
  getOwner:
    results:
      owner: AgentID // current owner of this smart contract
  getAmountOfRequiredFunds:
    params: 
      chargeWeight: Uint64
    results:
      tokenRequired: Uint64
  getTokenPerPackage:
    params:
      prodPass: ProductPass
    results: 
      tokenPerPackage: Uint64
