// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

package circularity

import "github.com/iotaledger/wasp/packages/wasmvm/wasmlib/go/wasmlib/wasmtypes"

type ArrayOfImmutableComposition struct {
	proxy wasmtypes.Proxy
}

func (a ArrayOfImmutableComposition) Length() uint32 {
	return a.proxy.Length()
}

func (a ArrayOfImmutableComposition) GetComposition(index uint32) ImmutableComposition {
	return ImmutableComposition{proxy: a.proxy.Index(index)}
}

type ImmutableCompositions = ArrayOfImmutableComposition

type ArrayOfMutableComposition struct {
	proxy wasmtypes.Proxy
}

func (a ArrayOfMutableComposition) AppendComposition() MutableComposition {
	return MutableComposition{proxy: a.proxy.Append()}
}

func (a ArrayOfMutableComposition) Clear() {
	a.proxy.ClearArray()
}

func (a ArrayOfMutableComposition) Length() uint32 {
	return a.proxy.Length()
}

func (a ArrayOfMutableComposition) GetComposition(index uint32) MutableComposition {
	return MutableComposition{proxy: a.proxy.Index(index)}
}

type MutableCompositions = ArrayOfMutableComposition

type ArrayOfImmutableFracComposition struct {
	proxy wasmtypes.Proxy
}

func (a ArrayOfImmutableFracComposition) Length() uint32 {
	return a.proxy.Length()
}

func (a ArrayOfImmutableFracComposition) GetFracComposition(index uint32) ImmutableFracComposition {
	return ImmutableFracComposition{proxy: a.proxy.Index(index)}
}

type ImmutableFracCompositions = ArrayOfImmutableFracComposition

type ArrayOfMutableFracComposition struct {
	proxy wasmtypes.Proxy
}

func (a ArrayOfMutableFracComposition) AppendFracComposition() MutableFracComposition {
	return MutableFracComposition{proxy: a.proxy.Append()}
}

func (a ArrayOfMutableFracComposition) Clear() {
	a.proxy.ClearArray()
}

func (a ArrayOfMutableFracComposition) Length() uint32 {
	return a.proxy.Length()
}

func (a ArrayOfMutableFracComposition) GetFracComposition(index uint32) MutableFracComposition {
	return MutableFracComposition{proxy: a.proxy.Index(index)}
}

type MutableFracCompositions = ArrayOfMutableFracComposition

type ArrayOfImmutableAgentID struct {
	proxy wasmtypes.Proxy
}

func (a ArrayOfImmutableAgentID) Length() uint32 {
	return a.proxy.Length()
}

func (a ArrayOfImmutableAgentID) GetAgentID(index uint32) wasmtypes.ScImmutableAgentID {
	return wasmtypes.NewScImmutableAgentID(a.proxy.Index(index))
}

type ImmutableFracPayoffKeys = ArrayOfImmutableAgentID

type ArrayOfMutableAgentID struct {
	proxy wasmtypes.Proxy
}

func (a ArrayOfMutableAgentID) AppendAgentID() wasmtypes.ScMutableAgentID {
	return wasmtypes.NewScMutableAgentID(a.proxy.Append())
}

func (a ArrayOfMutableAgentID) Clear() {
	a.proxy.ClearArray()
}

func (a ArrayOfMutableAgentID) Length() uint32 {
	return a.proxy.Length()
}

func (a ArrayOfMutableAgentID) GetAgentID(index uint32) wasmtypes.ScMutableAgentID {
	return wasmtypes.NewScMutableAgentID(a.proxy.Index(index))
}

type MutableFracPayoffKeys = ArrayOfMutableAgentID

type MapAgentIDToImmutableUint64 struct {
	proxy wasmtypes.Proxy
}

func (m MapAgentIDToImmutableUint64) GetUint64(key wasmtypes.ScAgentID) wasmtypes.ScImmutableUint64 {
	return wasmtypes.NewScImmutableUint64(m.proxy.Key(wasmtypes.AgentIDToBytes(key)))
}

type ImmutableFracPayoffs = MapAgentIDToImmutableUint64

type MapAgentIDToMutableUint64 struct {
	proxy wasmtypes.Proxy
}

func (m MapAgentIDToMutableUint64) Clear() {
	m.proxy.ClearMap()
}

func (m MapAgentIDToMutableUint64) GetUint64(key wasmtypes.ScAgentID) wasmtypes.ScMutableUint64 {
	return wasmtypes.NewScMutableUint64(m.proxy.Key(wasmtypes.AgentIDToBytes(key)))
}

type MutableFracPayoffs = MapAgentIDToMutableUint64

type ArrayOfImmutableRecyComposition struct {
	proxy wasmtypes.Proxy
}

func (a ArrayOfImmutableRecyComposition) Length() uint32 {
	return a.proxy.Length()
}

func (a ArrayOfImmutableRecyComposition) GetRecyComposition(index uint32) ImmutableRecyComposition {
	return ImmutableRecyComposition{proxy: a.proxy.Index(index)}
}

type ImmutableRecyCompositions = ArrayOfImmutableRecyComposition

type ArrayOfMutableRecyComposition struct {
	proxy wasmtypes.Proxy
}

func (a ArrayOfMutableRecyComposition) AppendRecyComposition() MutableRecyComposition {
	return MutableRecyComposition{proxy: a.proxy.Append()}
}

func (a ArrayOfMutableRecyComposition) Clear() {
	a.proxy.ClearArray()
}

func (a ArrayOfMutableRecyComposition) Length() uint32 {
	return a.proxy.Length()
}

func (a ArrayOfMutableRecyComposition) GetRecyComposition(index uint32) MutableRecyComposition {
	return MutableRecyComposition{proxy: a.proxy.Index(index)}
}

type MutableRecyCompositions = ArrayOfMutableRecyComposition
