// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

#![allow(dead_code)]
#![allow(unused_imports)]

use test3::*;
use wasmlib::*;
use wasmlib::host::*;

use crate::consts::*;
use crate::events::*;
use crate::keys::*;
use crate::params::*;
use crate::results::*;
use crate::state::*;

mod consts;
mod contract;
mod events;
mod keys;
mod params;
mod results;
mod state;
mod structs;
mod typedefs;
mod test3;

#[no_mangle]
fn on_load() {
    let exports = ScExports::new();
    exports.add_func(FUNC_ADD_MATERIAL,                 func_add_material_thunk);
    exports.add_func(FUNC_ADD_PP_TO_FRACTION,           func_add_pp_to_fraction_thunk);
    exports.add_func(FUNC_CREATE_FRACTION,              func_create_fraction_thunk);
    exports.add_func(FUNC_CREATE_PP,                    func_create_pp_thunk);
    exports.add_func(FUNC_CREATE_RECYCLATE,             func_create_recyclate_thunk);
    exports.add_func(FUNC_INIT,                         func_init_thunk);
    exports.add_func(FUNC_PAYOUT_FRAC,                  func_payout_frac_thunk);
    exports.add_func(FUNC_SET_MATERIALS,                func_set_materials_thunk);
    exports.add_func(FUNC_SET_OWNER,                    func_set_owner_thunk);
    exports.add_view(VIEW_GET_AMOUNT_OF_REQUIRED_FUNDS, view_get_amount_of_required_funds_thunk);
    exports.add_view(VIEW_GET_MATERIALS,                view_get_materials_thunk);
    exports.add_view(VIEW_GET_OWNER,                    view_get_owner_thunk);
    exports.add_view(VIEW_GET_PP,                       view_get_pp_thunk);
    exports.add_view(VIEW_GET_TOKEN_PER_PACKAGE,        view_get_token_per_package_thunk);

    unsafe {
        for i in 0..KEY_MAP_LEN {
            IDX_MAP[i] = get_key_id_from_string(KEY_MAP[i]);
        }
    }
}

pub struct AddMaterialContext {
	events:  test3Events,
	params: ImmutableAddMaterialParams,
	state: Mutabletest3State,
}

fn func_add_material_thunk(ctx: &ScFuncContext) {
	ctx.log("test3.funcAddMaterial");
	let f = AddMaterialContext {
		events:  test3Events {},
		params: ImmutableAddMaterialParams {
			id: OBJ_ID_PARAMS,
		},
		state: Mutabletest3State {
			id: OBJ_ID_STATE,
		},
	};
	ctx.require(f.params.id().exists(), "missing mandatory id");
	ctx.require(f.params.mat().exists(), "missing mandatory mat");
	ctx.require(f.params.prop().exists(), "missing mandatory prop");
	func_add_material(ctx, &f);
	ctx.log("test3.funcAddMaterial ok");
}

pub struct AddPPToFractionContext {
	events:  test3Events,
	params: ImmutableAddPPToFractionParams,
	results: MutableAddPPToFractionResults,
	state: Mutabletest3State,
}

fn func_add_pp_to_fraction_thunk(ctx: &ScFuncContext) {
	ctx.log("test3.funcAddPPToFraction");
	let f = AddPPToFractionContext {
		events:  test3Events {},
		params: ImmutableAddPPToFractionParams {
			id: OBJ_ID_PARAMS,
		},
		results: MutableAddPPToFractionResults {
			id: OBJ_ID_RESULTS,
		},
		state: Mutabletest3State {
			id: OBJ_ID_STATE,
		},
	};
	ctx.require(f.params.frac_id().exists(), "missing mandatory fracID");
	ctx.require(f.params.pp_id().exists(), "missing mandatory ppID");
	func_add_pp_to_fraction(ctx, &f);
	ctx.log("test3.funcAddPPToFraction ok");
}

pub struct CreateFractionContext {
	events:  test3Events,
	params: ImmutableCreateFractionParams,
	results: MutableCreateFractionResults,
	state: Mutabletest3State,
}

fn func_create_fraction_thunk(ctx: &ScFuncContext) {
	ctx.log("test3.funcCreateFraction");
	let f = CreateFractionContext {
		events:  test3Events {},
		params: ImmutableCreateFractionParams {
			id: OBJ_ID_PARAMS,
		},
		results: MutableCreateFractionResults {
			id: OBJ_ID_RESULTS,
		},
		state: Mutabletest3State {
			id: OBJ_ID_STATE,
		},
	};
	func_create_fraction(ctx, &f);
	ctx.log("test3.funcCreateFraction ok");
}

pub struct CreatePPContext {
	events:  test3Events,
	params: ImmutableCreatePPParams,
	results: MutableCreatePPResults,
	state: Mutabletest3State,
}

fn func_create_pp_thunk(ctx: &ScFuncContext) {
	ctx.log("test3.funcCreatePP");
	let f = CreatePPContext {
		events:  test3Events {},
		params: ImmutableCreatePPParams {
			id: OBJ_ID_PARAMS,
		},
		results: MutableCreatePPResults {
			id: OBJ_ID_RESULTS,
		},
		state: Mutabletest3State {
			id: OBJ_ID_STATE,
		},
	};
	ctx.require(f.params.name().exists(), "missing mandatory name");
	func_create_pp(ctx, &f);
	ctx.log("test3.funcCreatePP ok");
}

pub struct CreateRecyclateContext {
	events:  test3Events,
	params: ImmutableCreateRecyclateParams,
	results: MutableCreateRecyclateResults,
	state: Mutabletest3State,
}

fn func_create_recyclate_thunk(ctx: &ScFuncContext) {
	ctx.log("test3.funcCreateRecyclate");
	let f = CreateRecyclateContext {
		events:  test3Events {},
		params: ImmutableCreateRecyclateParams {
			id: OBJ_ID_PARAMS,
		},
		results: MutableCreateRecyclateResults {
			id: OBJ_ID_RESULTS,
		},
		state: Mutabletest3State {
			id: OBJ_ID_STATE,
		},
	};
	ctx.require(f.params.frac_id().exists(), "missing mandatory fracID");
	func_create_recyclate(ctx, &f);
	ctx.log("test3.funcCreateRecyclate ok");
}

pub struct InitContext {
	events:  test3Events,
	params: ImmutableInitParams,
	state: Mutabletest3State,
}

fn func_init_thunk(ctx: &ScFuncContext) {
	ctx.log("test3.funcInit");
	let f = InitContext {
		events:  test3Events {},
		params: ImmutableInitParams {
			id: OBJ_ID_PARAMS,
		},
		state: Mutabletest3State {
			id: OBJ_ID_STATE,
		},
	};
	func_init(ctx, &f);
	ctx.log("test3.funcInit ok");
}

pub struct PayoutFracContext {
	events:  test3Events,
	params: ImmutablePayoutFracParams,
	state: Mutabletest3State,
}

fn func_payout_frac_thunk(ctx: &ScFuncContext) {
	ctx.log("test3.funcPayoutFrac");
	let f = PayoutFracContext {
		events:  test3Events {},
		params: ImmutablePayoutFracParams {
			id: OBJ_ID_PARAMS,
		},
		state: Mutabletest3State {
			id: OBJ_ID_STATE,
		},
	};
	ctx.require(f.params.frac_id().exists(), "missing mandatory fracID");
	func_payout_frac(ctx, &f);
	ctx.log("test3.funcPayoutFrac ok");
}

pub struct SetMaterialsContext {
	events:  test3Events,
	params: ImmutableSetMaterialsParams,
	state: Mutabletest3State,
}

fn func_set_materials_thunk(ctx: &ScFuncContext) {
	ctx.log("test3.funcSetMaterials");
	let f = SetMaterialsContext {
		events:  test3Events {},
		params: ImmutableSetMaterialsParams {
			id: OBJ_ID_PARAMS,
		},
		state: Mutabletest3State {
			id: OBJ_ID_STATE,
		},
	};
	ctx.require(f.params.id().exists(), "missing mandatory id");
	func_set_materials(ctx, &f);
	ctx.log("test3.funcSetMaterials ok");
}

pub struct SetOwnerContext {
	events:  test3Events,
	params: ImmutableSetOwnerParams,
	state: Mutabletest3State,
}

fn func_set_owner_thunk(ctx: &ScFuncContext) {
	ctx.log("test3.funcSetOwner");

	// current owner of this smart contract
	let access = ctx.state().get_agent_id("owner");
	ctx.require(access.exists(), "access not set: owner");
	ctx.require(ctx.caller() == access.value(), "no permission");

	let f = SetOwnerContext {
		events:  test3Events {},
		params: ImmutableSetOwnerParams {
			id: OBJ_ID_PARAMS,
		},
		state: Mutabletest3State {
			id: OBJ_ID_STATE,
		},
	};
	ctx.require(f.params.owner().exists(), "missing mandatory owner");
	func_set_owner(ctx, &f);
	ctx.log("test3.funcSetOwner ok");
}

pub struct GetAmountOfRequiredFundsContext {
	params: ImmutableGetAmountOfRequiredFundsParams,
	results: MutableGetAmountOfRequiredFundsResults,
	state: Immutabletest3State,
}

fn view_get_amount_of_required_funds_thunk(ctx: &ScViewContext) {
	ctx.log("test3.viewGetAmountOfRequiredFunds");
	let f = GetAmountOfRequiredFundsContext {
		params: ImmutableGetAmountOfRequiredFundsParams {
			id: OBJ_ID_PARAMS,
		},
		results: MutableGetAmountOfRequiredFundsResults {
			id: OBJ_ID_RESULTS,
		},
		state: Immutabletest3State {
			id: OBJ_ID_STATE,
		},
	};
	ctx.require(f.params.charge_weight().exists(), "missing mandatory chargeWeight");
	view_get_amount_of_required_funds(ctx, &f);
	ctx.log("test3.viewGetAmountOfRequiredFunds ok");
}

pub struct GetMaterialsContext {
	params: ImmutableGetMaterialsParams,
	results: MutableGetMaterialsResults,
	state: Immutabletest3State,
}

fn view_get_materials_thunk(ctx: &ScViewContext) {
	ctx.log("test3.viewGetMaterials");
	let f = GetMaterialsContext {
		params: ImmutableGetMaterialsParams {
			id: OBJ_ID_PARAMS,
		},
		results: MutableGetMaterialsResults {
			id: OBJ_ID_RESULTS,
		},
		state: Immutabletest3State {
			id: OBJ_ID_STATE,
		},
	};
	ctx.require(f.params.id().exists(), "missing mandatory id");
	view_get_materials(ctx, &f);
	ctx.log("test3.viewGetMaterials ok");
}

pub struct GetOwnerContext {
	results: MutableGetOwnerResults,
	state: Immutabletest3State,
}

fn view_get_owner_thunk(ctx: &ScViewContext) {
	ctx.log("test3.viewGetOwner");
	let f = GetOwnerContext {
		results: MutableGetOwnerResults {
			id: OBJ_ID_RESULTS,
		},
		state: Immutabletest3State {
			id: OBJ_ID_STATE,
		},
	};
	view_get_owner(ctx, &f);
	ctx.log("test3.viewGetOwner ok");
}

pub struct GetPPContext {
	params: ImmutableGetPPParams,
	results: MutableGetPPResults,
	state: Immutabletest3State,
}

fn view_get_pp_thunk(ctx: &ScViewContext) {
	ctx.log("test3.viewGetPP");
	let f = GetPPContext {
		params: ImmutableGetPPParams {
			id: OBJ_ID_PARAMS,
		},
		results: MutableGetPPResults {
			id: OBJ_ID_RESULTS,
		},
		state: Immutabletest3State {
			id: OBJ_ID_STATE,
		},
	};
	ctx.require(f.params.id().exists(), "missing mandatory id");
	view_get_pp(ctx, &f);
	ctx.log("test3.viewGetPP ok");
}

pub struct GetTokenPerPackageContext {
	params: ImmutableGetTokenPerPackageParams,
	results: MutableGetTokenPerPackageResults,
	state: Immutabletest3State,
}

fn view_get_token_per_package_thunk(ctx: &ScViewContext) {
	ctx.log("test3.viewGetTokenPerPackage");
	let f = GetTokenPerPackageContext {
		params: ImmutableGetTokenPerPackageParams {
			id: OBJ_ID_PARAMS,
		},
		results: MutableGetTokenPerPackageResults {
			id: OBJ_ID_RESULTS,
		},
		state: Immutabletest3State {
			id: OBJ_ID_STATE,
		},
	};
	ctx.require(f.params.prod_pass().exists(), "missing mandatory prodPass");
	view_get_token_per_package(ctx, &f);
	ctx.log("test3.viewGetTokenPerPackage ok");
}
