// Copyright 2020 IOTA Stiftung
// SPDX-License-Identifier: Apache-2.0

// (Re-)generated by schema tool
// >>>> DO NOT CHANGE THIS FILE! <<<<
// Change the json schema instead

#![allow(dead_code)]

use wasmlib::*;
use wasmlib::host::*;
use crate::structs::*;

pub struct ArrayOfImmutableComposition {
	pub(crate) obj_id: i32,
}

impl ArrayOfImmutableComposition {
    pub fn length(&self) -> i32 {
        get_length(self.obj_id)
    }

	pub fn get_composition(&self, index: i32) -> ImmutableComposition {
		ImmutableComposition { obj_id: self.obj_id, key_id: Key32(index) }
	}
}

pub type ImmutableCompositions = ArrayOfImmutableComposition;

pub struct ArrayOfMutableComposition {
	pub(crate) obj_id: i32,
}

impl ArrayOfMutableComposition {
    pub fn clear(&self) {
        clear(self.obj_id);
    }

    pub fn length(&self) -> i32 {
        get_length(self.obj_id)
    }

	pub fn get_composition(&self, index: i32) -> MutableComposition {
		MutableComposition { obj_id: self.obj_id, key_id: Key32(index) }
	}
}

pub type MutableCompositions = ArrayOfMutableComposition;

pub struct ArrayOfImmutableFracComposition {
	pub(crate) obj_id: i32,
}

impl ArrayOfImmutableFracComposition {
    pub fn length(&self) -> i32 {
        get_length(self.obj_id)
    }

	pub fn get_frac_composition(&self, index: i32) -> ImmutableFracComposition {
		ImmutableFracComposition { obj_id: self.obj_id, key_id: Key32(index) }
	}
}

pub type ImmutableFracCompositions = ArrayOfImmutableFracComposition;

pub struct ArrayOfMutableFracComposition {
	pub(crate) obj_id: i32,
}

impl ArrayOfMutableFracComposition {
    pub fn clear(&self) {
        clear(self.obj_id);
    }

    pub fn length(&self) -> i32 {
        get_length(self.obj_id)
    }

	pub fn get_frac_composition(&self, index: i32) -> MutableFracComposition {
		MutableFracComposition { obj_id: self.obj_id, key_id: Key32(index) }
	}
}

pub type MutableFracCompositions = ArrayOfMutableFracComposition;

pub struct ArrayOfImmutableRecyComposition {
	pub(crate) obj_id: i32,
}

impl ArrayOfImmutableRecyComposition {
    pub fn length(&self) -> i32 {
        get_length(self.obj_id)
    }

	pub fn get_recy_composition(&self, index: i32) -> ImmutableRecyComposition {
		ImmutableRecyComposition { obj_id: self.obj_id, key_id: Key32(index) }
	}
}

pub type ImmutableRecyCompositions = ArrayOfImmutableRecyComposition;

pub struct ArrayOfMutableRecyComposition {
	pub(crate) obj_id: i32,
}

impl ArrayOfMutableRecyComposition {
    pub fn clear(&self) {
        clear(self.obj_id);
    }

    pub fn length(&self) -> i32 {
        get_length(self.obj_id)
    }

	pub fn get_recy_composition(&self, index: i32) -> MutableRecyComposition {
		MutableRecyComposition { obj_id: self.obj_id, key_id: Key32(index) }
	}
}

pub type MutableRecyCompositions = ArrayOfMutableRecyComposition;
